apiVersion: v1
kind: Secret
metadata:
  name: db-credentials        # this is the name pods will reference
  namespace: default          # same namespace as your app
type: Opaque                  # Opaque = general purpose secret
stringData:                   # stringData lets you write plain text (K8s encodes it)
  DB_HOST: "shop-webapp-db.cj26mkqccjhj.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "shopdb"
  DB_USERNAME: "admin"
  DB_PASSWORD: "Admin1234"
