apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-webapp
  template:
    metadata:
      labels:
        app: shop-webapp
    spec:
      containers:
        - name: shop-webapp
          image: 720546261973.dkr.ecr.ap-south-1.amazonaws.com/shop-webapp-ecr:latest
          ports:
            - containerPort: 8080
